bump_version: null
lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  nextflow_config:
    - params.input
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: test
  description: test
  force: true
  is_nfcore: true
  name: stableexpression
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0dev
update: null
