name: variation_coefficient
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base==4.3.3
  - conda-forge::r-optparse==1.7.5
  - conda-forge::r-data.table==1.15.4
  - conda-forge::r-dplyr==1.1.4
  - conda-forge::r-tibble==3.2.1
